### ISSUE TITLE
User auth 

### ISSUE THREAD

**Issue by Tianyou-Song** [Tianyou-Song/MusicMist#2]
User auth done... I hope

**Comment by s-pangburn** [comment]
Hi Tim! This is looking great! You really only have two issues with your errors:

- [ ] Errors need a little more padding on the top (too close to Submit button) and need to be centered.
- [ ] New errors merge with the old errors instead of overwriting them:
![screen shot 2018-10-15 at 5 23 05 pm](https://user-images.githubusercontent.com/8031316/46985426-46bd7900-d09f-11e8-8d59-744cdb1d677f.png)
  - Notice how it says "Email has already been taken" but also that "Email can't be blank". This shouldn't be possible.

That's really it though! Great job, Tim! What's here is fairly polished 🙂

**Comment by Tianyou-Song** [comment]
Errors fixed.  
Took out the old state altogether form errors reducer, not sure if I will need the old state later.

```javascript
export default (state = [], action) => {
  Object.freeze(state);
  switch (action.type) {
    case RECEIVE_ERRORS:
      return union([], action.errors.responseJSON);
    case CLEAR_ERRORS:
      return [];
    default:
      return [];
  }
};
```

**Comment by s-pangburn** [comment]
Hi Tim!

- [ ] I managed to center the errors by setting `width: 90%` and `text-align: center` on your `.errors` CSS class. Maybe give that a shot?

- [ ] Also, there should be a link in your modal to switch between forms ("Not a user? Sign up" or "Already a user? Sign in) and the errors should clear when switching.

**Comment by Tianyou-Song** [comment]
Woops, forgot about centering. It is fixed.
I have added the switch buttons as well, although they are not present on the actual SoundCloud forms.

**Comment by s-pangburn** [comment]
Oh, I meant more of a text link, since having two buttons is confusing (similar to what you see [at the bottom of this example](https://www.evernote.com/Login.action)). See if you can make that work?

Since SoundCloud doesn't have it though, I guess I can make it optional 🙂 I'll mark this MVP as complete, but definitely remove the extra button, it's just really confusing looking. Either replace it with a text link like in the example or remove it altogether.
